core/urls.py
from django.urls import path,include

from .views import ContactView, HomeView,AboutView, ProjectView,ProjectUnoView


app_name='core'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('about/',AboutView.as_view(),name='about'),
    path('project/',ProjectView.as_view(),name='project'),
    path('contact/',ContactView.as_view(),name='contact'),
    
    path('uno/',ProjectUnoView.as_view(),name='uno'),
    
    
]

pdf_to_word/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    
    path('',include('core.urls',namespace='core')),
    path('admin/', admin.site.urls),
    
    
]

#custom titles for admin
admin.site.site_header = "Cenabast"
admin.site.index_title = "Panel de Administrador"
admin.site.site_title = "Cenabast"

core/models.py
from ast import Pass
from django.db import models

# Create your models here.

class Post(models.Model):
    title=models.CharField(verbose_name='Titulo', max_length=250)
    content=models.TextField(verbose_name='Contenido')

    def __str__(self):
        return "%s %s" % (self.title, self.content)
# ------------------------------------------------------------------------------    
class Clase(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion= models.TextField()
    
    
    def __str__(self):
        return "%s %s" % (self.nombre, self.descripcion)
    
# ------------------------------------------------------------------------------    
class Estudiante(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos= models.TextField()    
    
    def __str__(self):
        return "%s %s" % (self.nombre, self.apellidos)
    
# ------------------------------------------------------------------------------    
class Matricula(models.Model):
    clases = models.ForeignKey(Clase,on_delete=models.PROTECT)
    estudiantes= models.ForeignKey(Estudiante,on_delete=models.PROTECT)
    notas=models.FloatField()    
    def __str__(self):
        return "%s %s %s" % (self.clases, self.estudiantes,self.notas) 

core/forms.py
# todo: Formulario

# !libreria de django para formularios
from dataclasses import field, fields
from django import forms

# !traemos el modelo de blogs
from .models import Post


# !Formulario para crear un post desde la vista a la BBDD
class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post # *traemos el modelo
        fields=('title','content') # *traemos los campos del modelo
        

core/views.py
from django.shortcuts import render,redirect,get_object_or_404,redirect
from django.views.generic import View


#! traemos la clase de froms.py PostCreateForm
from .forms import PostCreateForm
from .models import Post

#! importamos de django
from django.urls import reverse_lazy



class HomeView(View):
    def get(self,request, *args, **kwargs):
        context={
            
        }
        return render(request,'core/home.html',context)
# ------------------------------------------------------------------------------------------------------    
    
class AboutView(View):
    def get(self,request, *args, **kwargs):
        context={
            
        }
        return render(request,'core/about.html',context)
# ------------------------------------------------------------------------------------------------------  
class ProjectView(View):
    def get(self,request, *args, **kwargs):
        context={
            
        }
        return render(request,'core/project.html',context)
    
# ------------------------------------------------------------------------------------------------------  
class ContactView(View):
    def get(self,request, *args, **kwargs):
        context={
            
        }
        return render(request,'core/contact.html',context)
    
# ------------------------------------------------------------------------------------------------------  

class ProjectUnoView(View):
    
    def get(self,request,*args, **kwargs):
        form=PostCreateForm() #?pasamos la clase form de traida de forms.py a una variable llamada form
        context={
            'form':form
        }
        return render(request,'core/proyecto1.html',context)
    
    #todo el get los cambiamos a post dentro de la misma clase
    def post(self,request,*args, **kwargs):
        
        if request.method == "POST": #?si el metodo es post
            form=PostCreateForm(request.POST) #? traeme el formulario y toda la info que esta dentro de post(request.POST) en el formulario en la pagina create
            
            if form.is_valid(): #? si el formulario es valido obtenemos el titulo y el contenido la info que ingresamos en la pagina create
                title = form.cleaned_data.get('title') #? aqui obtenemos lo que ingresamos en el campo title del formulario
                content = form.cleaned_data.get('content') #? aqui obtenemos lo que ingresamos en el campo content del formulario
                
                
                p,created = Post.objects.get_or_create(title=title, content=content) #? Al modelo Post (BBDD) le asiganamos lo que tenemos en el formulario
                p.save() #? guardamos la informacion en el modelo de la BBDD
                return redirect('core:home') #? lo redireccionamos al home
            
        context={
            
        }
        return render(request,'core/projecto1.html',context)
    
# ------------------------------------------------------------------------------------------------------     
    
    

    

core/templates/core/about.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
  <h1>Hola About!!!!!!</h1>
{% endblock content %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>PETUNIA</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'core:home' %}">Linda PETU PETU</a>
                <!-- <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button> -->
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:project' %}">Projects</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:contact' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">

            <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
                <div class="d-flex justify-content-center">
                    <div class="text-center">
                        {% block content %}
                          
                        {% endblock content %}
                        
                    </div>
                </div>
            </div>
        </header>   
        
     
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; petunita 2022</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

core/templates/core/base2.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
      
    {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    <div class="container text-center">
    {% block header %}
      
    {% endblock header %}
  </div>

    <div class="container">

    {% block content %}
      
    {% endblock content %}

  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <h1>Hola Contacto!!!!!</h1>
{% endblock content %}

core/templates/core/home.html
{% extends "core/base.html" %} {% load static %} {% block content %}
<!-- <h1 class="mx-auto my-0 text-uppercase">Grayscale</h1>
<h2 class="text-white-50 mx-auto mt-2 mb-5">A free, responsive, one page Bootstrap theme created by Start Bootstrap.</h2>
<a class="btn btn-primary" href="#about">Get Started</a> -->
<table class="table">
  <thead>
    <tr>
      <th scope="col">Proyectos</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <!-- <th scope="row">1</th> -->
      <td>
        <a href="{% url 'core:uno' %}" type="button" class="btn btn-primary">Proyecto 1</a>
      </td>
    </tr>
    <tr>
      <!-- <th scope="row">2</th> -->
      <td>
        <a href="#" type="button" class="btn btn-secondary">Proyecto 3</a>
      </td>
    </tr>
    <tr>
      <!-- <th scope="row">3</th> -->
      <td>
        <a href="#" type="button" class="btn btn-success">Proyecto 3</a>
      </td>
    </tr>
  </tbody>
</table>
{% endblock content %}

core/templates/core/project.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    <h1>Hola Proyectos!!!!!</h1>
{% endblock content %}

core/templates/core/proyecto1.html
{% extends "core/base2.html" %}

{% block title %}
  documento bursatil
{% endblock title %}

{% block header %}
<style></style>
  <h1>Creacion documento petunio</h1>
{% endblock header %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label for="" class="form-label">Titulo</label>
    <input
      type="text"
      class="form-control"
      id="exampleInputEmail1"
      aria-describedby=""
      {{ form.title }}
      
    
    <div id="emailHelp" class="form-text">
      
    </div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Descripcion</label>
    <input type="text" class="form-control"  {{ form.content }} 
  </div>
 
  <button type="submit" class="btn btn-primary">Crear</button>
</form>

<br>
<br>


<a href="{% url 'core:home' %}" type="button" class="btn btn-success">Volver</a>
{% endblock content %}